# Form implementation generated from reading ui file 'add_clients.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_add_clients(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(471, 370)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(290, 90, 91, 18))
        self.label_3.setObjectName("label_3")
        self.te_cl_name = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.te_cl_name.setGeometry(QtCore.QRect(10, 40, 401, 31))
        self.te_cl_name.setObjectName("te_cl_name")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 71, 18))
        self.label_4.setObjectName("label_4")
        self.te_cl_pass = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.te_cl_pass.setGeometry(QtCore.QRect(120, 110, 151, 31))
        self.te_cl_pass.setObjectName("te_cl_pass")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(120, 90, 61, 18))
        self.label_7.setObjectName("label_7")
        self.te_cl_license = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.te_cl_license.setGeometry(QtCore.QRect(10, 110, 71, 31))
        self.te_cl_license.setObjectName("te_cl_license")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 71, 18))
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 71, 18))
        self.label_11.setObjectName("label_11")
        self.te_cl_phone = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.te_cl_phone.setGeometry(QtCore.QRect(10, 180, 161, 31))
        self.te_cl_phone.setObjectName("te_cl_phone")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(190, 160, 61, 18))
        self.label_12.setObjectName("label_12")
        self.te_cl_mail = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.te_cl_mail.setGeometry(QtCore.QRect(190, 180, 221, 31))
        self.te_cl_mail.setObjectName("te_cl_mail")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(190, 230, 81, 18))
        self.label_13.setObjectName("label_13")
        self.te_cl_citizenship = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.te_cl_citizenship.setGeometry(QtCore.QRect(190, 250, 221, 31))
        self.te_cl_citizenship.setObjectName("te_cl_citizenship")
        self.label_14 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 230, 181, 18))
        self.label_14.setObjectName("label_14")
        self.sb_cl_experience = QtWidgets.QSpinBox(parent=self.groupBox)
        self.sb_cl_experience.setGeometry(QtCore.QRect(290, 110, 52, 32))
        self.sb_cl_experience.setObjectName("sb_cl_experience")
        self.te_cl_language = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.te_cl_language.setGeometry(QtCore.QRect(10, 250, 141, 31))
        self.te_cl_language.setObjectName("te_cl_language")
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавить запись (Clients)"))
        self.label_3.setText(_translate("Dialog", "cl_experience"))
        self.label_4.setText(_translate("Dialog", "cl_name"))
        self.label_7.setText(_translate("Dialog", "cl_pass"))
        self.label_5.setText(_translate("Dialog", "cl_license"))
        self.label_11.setText(_translate("Dialog", "cl_phone"))
        self.label_12.setText(_translate("Dialog", "cl_mail"))
        self.label_13.setText(_translate("Dialog", "cl_citizenship"))
        self.label_14.setText(_translate("Dialog", "cl_language"))
