# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_add_branches(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(471, 277)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 181, 18))
        self.label.setObjectName("label")
        self.te_br_numb = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.te_br_numb.setGeometry(QtCore.QRect(10, 40, 181, 31))
        self.te_br_numb.setObjectName("te_br_numb")
        self.te_br_city = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.te_br_city.setGeometry(QtCore.QRect(240, 100, 181, 31))
        self.te_br_city.setObjectName("te_br_city")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(240, 80, 181, 18))
        self.label_3.setObjectName("label_3")
        self.te_br_region = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.te_br_region.setGeometry(QtCore.QRect(240, 40, 181, 31))
        self.te_br_region.setObjectName("te_br_region")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(240, 20, 181, 18))
        self.label_4.setObjectName("label_4")
        self.te_br_addr = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.te_br_addr.setGeometry(QtCore.QRect(10, 160, 421, 31))
        self.te_br_addr.setObjectName("te_br_addr")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 140, 181, 18))
        self.label_7.setObjectName("label_7")
        self.te_br_district = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.te_br_district.setGeometry(QtCore.QRect(10, 100, 181, 31))
        self.te_br_district.setObjectName("te_br_district")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 181, 18))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавить запись (Branches)"))
        self.label.setText(_translate("Dialog", "br_numb"))
        self.label_3.setText(_translate("Dialog", "br_city"))
        self.label_4.setText(_translate("Dialog", "br_region"))
        self.label_7.setText(_translate("Dialog", "br_addr"))
        self.label_5.setText(_translate("Dialog", "br_district"))
